version: "3"
containers:
- name: workshop
  image: nadvolod/durable-ai-agents-modules-sandbox:latest
  shell: /bin/bash
  memory: 4096
  ports:
  - 5000
  - 8233
secrets:
- name: TEMPORAL_LITELLM_BROKER_SECRET
